/*
=====================================================
Project : End-to-End Retail ETL Pipeline using Snowflake
Module  : Customer ETL
Author  : Shweta Mujmer
=====================================================
*/

/*CREATING TABLE CUSTOMERS_STG UNDER RAW SCHEMA*/

CREATE TABLE RAW.CUSTOMERS_STG (
    CUSTOMER_ID NUMBER,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    CONTACT_NO VARCHAR(20),
    DOB DATE,
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    REGISTRATION_DATE DATE,
    LAST_UPDATED TIMESTAMP,RETAIL_DB.RAW.CUSTOMERS_STG,
   );

    /*CREATING TABLE PRODUCTS_STG UNDER RAW SCHEMA*/

   CREATE OR REPLACE TABLE RAW.PRODUCTS_STG(
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(50),
    CATEGORY VARCHAR(50),
    PRICE NUMBER(10,2) ,
    STOCK_QUANTITY NUMBER,
    STATUS VARCHAR(20) ,
    LAST_UPDATED TIMESTAMP
    );

    /*CREATING TABLE ORDERS_STG UNDER RAW SCHEMA*/

    CREATE OR REPLACE TABLE RAW.ORDERS_STG(
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER ,
    PRODUCT_ID NUMBER ,
    QUANTITY NUMBER ,
    ORDER_DATE DATE ,
    ORDER_STATUS VARCHAR(20) ,
    TOTAL_AMOUNT NUMBER(10,2) ,
    LAST_UPDATED TIMESTAMP
    );

    /*CREATING PAYMENTS_STG UNDER RAW SCHEMA*/

    CREATE TABLE RAW.PAYMENTS_STG( 
    PAYMENT_ID NUMBER,
    ORDER_ID NUMBER,
    PAYMENT_MODE VARCHAR(20),
    PAYMENT_DATE DATE,
    PAYMENT_STATUS VARCHAR(20),
    AMOUNT NUMBER(10,2),
    LAST_UPDATED TIMESTAMP
    );

