/*
=====================================================
Project : End-to-End Retail ETL Pipeline using Snowflake
Module  : Customer ETL
Author  : Shweta Mujmer
=====================================================
*/
           //*Create all curated tables*//

  /* CREATING CURATED CUSTOMER TABLE*/ 

CREATE OR REPLACE TABLE CURATED.CUSTOMERS( 
    CUSTOMER_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CONTACT_NO VARCHAR(20),
    DOB DATE,
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    REGISTRATION_DATE DATE,
    LAST_UPDATED TIMESTAMP
    );

/* CREATING CURATED PRODUCT TABLE*/

CREATE OR REPLACE TABLE CURATED.PRODUCTS
   (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    PRICE NUMBER(10,2) NOT NULL,
    STOCK_QUANTITY NUMBER NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    LAST_UPDATED TIMESTAMP
    );

/* CREATING CURATED ORDER TABLE*/

CREATE OR REPLACE TABLE CURATED.ORDERS
   (
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER CHECK (QUANTITY > 0),
    ORDER_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR(20) NOT NULL,
    TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
    LAST_UPDATED TIMESTAMP
    );

/* CREATING CURATED PAYMENT TABLE*/

CREATE TABLE CURATED.PAYMENTS
( 
PAYMENT_ID NUMBER PRIMARY KEY,
ORDER_ID NUMBER NOT NULL,
PAYMENT_MODE VARCHAR(20)NOT NULL,
PAYMENT_DATE DATE NOT NULL,
PAYMENT_STATUS VARCHAR(20) NOT NULL,
AMOUNT NUMBER(10,2)NOT NULL,
LAST_UPDATED TIMESTAMP
);

     //*Rejected tables*//

/*SCHEMA - REJECT TABLE - CUSTOMERS_REJECT*/

CREATE TABLE REJECT.CUSTOMERS_REJECT 
    (
    CUSTOMER_ID NUMBER,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    CONTACT_NO VARCHAR(20),
    DOB DATE,
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    REGISTRATION_DATE DATE,
    LAST_UPDATED TIMESTAMP,

    REJECT_REASON VARCHAR(255),
    FILE_NAME VARCHAR(100),
    LOAD_TIMESTAMP TIMESTAMP
    );

/*SCHEMA - REJECT TABLE - PRODUCTS_REJECT*/

CREATE OR REPLACE TABLE REJECT.PRODUCTS_REJECT
    (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(50),
    CATEGORY VARCHAR(50),
    PRICE NUMBER(10,2) ,
    STOCK_QUANTITY NUMBER,
    STATUS VARCHAR(20) ,
    LAST_UPDATED TIMESTAMP,
    
    REJECT_REASON VARCHAR(255),
    FILE_NAME VARCHAR(100),
    LOAD_TIMESTAMP TIMESTAMP
    );

/*SCHEMA - REJECT TABLE - ORDERS_REJECT*/

 CREATE OR REPLACE TABLE REJECT.ORDERS_REJECT
    (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER ,
    PRODUCT_ID NUMBER ,
    QUANTITY NUMBER ,
    ORDER_DATE DATE ,
    ORDER_STATUS VARCHAR(20) ,
    TOTAL_AMOUNT NUMBER(10,2) ,
    LAST_UPDATED TIMESTAMP,

    REJECT_REASON VARCHAR(255),
    FILE_NAME VARCHAR(100),
    LOAD_TIMESTAMP TIMESTAMP
    );

/*SCHEMA - REJECT TABLE - PAYMENTS_REJECT*/
   
CREATE TABLE REJECT.PAYMENTS_REJECT
( 
PAYMENT_ID NUMBER,
ORDER_ID NUMBER,
PAYMENT_MODE VARCHAR(20),
PAYMENT_DATE DATE,
PAYMENT_STATUS VARCHAR(20),
AMOUNT NUMBER(10,2),
LAST_UPDATED TIMESTAMP,

REJECT_REASON VARCHAR(255),
FILE_NAME VARCHAR(100),
LOAD_TIMESTAMP TIMESTAMP
);

  //*Create the AUDIT_LOG table.*//

  /* create audit schema*/
CREATE SCHEMA METADATA;

CREATE OR REPLACE TABLE METADATA.AUDIT_LOG
   (
    RUN_ID NUMBER AUTOINCREMENT,
    PIPELINE_NAME VARCHAR(50),
    FILE_NAME VARCHAR(100),
    LOAD_START_TIME TIMESTAMP,
    LOAD_END_TIME TIMESTAMP,
    STATUS VARCHAR(20),
    ROWS_READ NUMBER,
    ROWS_LOADED NUMBER,
    ROWS_REJECTED NUMBER,
    ERROR_MESSAGE VARCHAR(500)
    );

