/*
=====================================================
Project : End-to-End Retail ETL Pipeline using Snowflake
Module  : Customer ETL
Author  : Shweta Mujmer
=====================================================
*/

/*COPY INTO RAW.CUSTOMERS_STG*/

COPY INTO RAW.CUSTOMERS_STG
FROM @RAW.RETAIL_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_FILE_FORMAT')
ON_ERROR = 'CONTINUE';

 /*Validation using ROW_NUMBER()*/

SELECT *
FROM (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY CUSTOMER_ID
            ORDER BY LAST_UPDATED DESC
        ) AS RN
    FROM RAW.CUSTOMERS_STG
)
WHERE RN = 1;

/* VIEW TRANSFORMED FROM RAW.CUSTOMERS_STG*/

SELECT
    CUSTOMER_ID,
    TRIM(FIRST_NAME) AS FIRST_NAME,
    TRIM(LAST_NAME) AS LAST_NAME,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    TRIM(CONTACT_NO) AS CONTACT_NO,
    DOB,
    TRIM(ADDRESS) AS ADDRESS,
    INITCAP(TRIM(CITY)) AS CITY,
    INITCAP(TRIM(STATE)) AS STATE,
    INITCAP(TRIM(COUNTRY)) AS COUNTRY,
    REGISTRATION_DATE,
    LAST_UPDATED
FROM
(
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY CUSTOMER_ID
               ORDER BY LAST_UPDATED DESC
           ) AS RN
    FROM RAW.CUSTOMERS_STG
)
WHERE RN = 1
  AND CUSTOMER_ID IS NOT NULL
  AND FIRST_NAME IS NOT NULL
  AND EMAIL IS NOT NULL
  AND EMAIL LIKE '%@%';

  /* Insert valid records from RAW.CUSTOMERS_STG into CURATED.CUSTOMERS */

  INSERT INTO CURATED.CUSTOMERS
  SELECT
    CUSTOMER_ID,
    TRIM(FIRST_NAME),
    TRIM(LAST_NAME),
    LOWER(TRIM(EMAIL)),
    TRIM(CONTACT_NO),
    DOB,
    TRIM(ADDRESS),
    INITCAP(TRIM(CITY)),
    INITCAP(TRIM(STATE)),
    INITCAP(TRIM(COUNTRY)),
    REGISTRATION_DATE,
    LAST_UPDATED
FROM
(
    SELECT *,
           ROW_NUMBER() OVER
           (
               PARTITION BY CUSTOMER_ID
               ORDER BY LAST_UPDATED DESC
           ) AS RN
    FROM RAW.CUSTOMERS_STG
)
WHERE RN = 1
AND CUSTOMER_ID IS NOT NULL
AND FIRST_NAME IS NOT NULL
AND EMAIL IS NOT NULL
AND EMAIL LIKE '%@%';

/*End of Curated Load*/

/* INSERT INTO REJECT.CUSTOMERS_REJECT*/

  INSERT INTO REJECT.CUSTOMERS_REJECT
(
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    CONTACT_NO,
    DOB,
    ADDRESS,
    CITY,
    STATE,
    COUNTRY,
    REGISTRATION_DATE,
    LAST_UPDATED,
    REJECT_REASON,
    FILE_NAME,
    LOAD_TIMESTAMP
)

SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    CONTACT_NO,
    DOB,
    ADDRESS,
    CITY,
    STATE,
    COUNTRY,
    REGISTRATION_DATE,
    LAST_UPDATED,

CASE
    WHEN RN > 1 THEN 'Duplicate CUSTOMER_ID'
    WHEN CUSTOMER_ID IS NULL THEN 'CUSTOMER_ID is NULL'
    WHEN FIRST_NAME IS NULL THEN 'FIRST_NAME is NULL'
    WHEN EMAIL IS NULL THEN 'EMAIL is NULL'
    WHEN EMAIL NOT LIKE '%@%' THEN 'Invalid Email Format'
END AS REJECT_REASON,

    'CUSTOMERS.csv' AS FILE_NAME,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP

FROM
(
    SELECT *,
           ROW_NUMBER() OVER
           (
               PARTITION BY CUSTOMER_ID
               ORDER BY LAST_UPDATED DESC
           ) AS RN
    FROM RAW.CUSTOMERS_STG
) 

WHERE RN > 1
   OR CUSTOMER_ID IS NULL
   OR FIRST_NAME IS NULL
   OR EMAIL IS NULL
   OR EMAIL NOT LIKE '%@%';

  /*end reject handling*/

/*creating incremental loading for customer table*/

   MERGE INTO CURATED.CUSTOMERS AS T

USING
(
    SELECT *
    FROM
    (
        SELECT *,
               ROW_NUMBER() OVER
               (
                   PARTITION BY CUSTOMER_ID
                   ORDER BY LAST_UPDATED DESC
               ) AS RN
        FROM RAW.CUSTOMERS_STG
    )
    WHERE RN = 1
      AND CUSTOMER_ID IS NOT NULL
      AND FIRST_NAME IS NOT NULL
      AND EMAIL IS NOT NULL
      AND EMAIL LIKE '%@%'
) AS S

ON T.CUSTOMER_ID = S.CUSTOMER_ID

WHEN MATCHED THEN
UPDATE SET
    T.CUSTOMER_ID = S.CUSTOMER_ID,
    T.FIRST_NAME = S.FIRST_NAME,
    T.LAST_NAME = S.LAST_NAME,
    T.EMAIL = S.EMAIL ,
    T.CONTACT_NO = S.CONTACT_NO,
    T.DOB = S.DOB,
    T.ADDRESS = S.ADDRESS,
    T.CITY = S.CITY,
    T.STATE = S.STATE,
    T.COUNTRY = S.COUNTRY,
    T.REGISTRATION_DATE = S.REGISTRATION_DATE,
    T.LAST_UPDATED = S.LAST_UPDATED

WHEN NOT MATCHED THEN
INSERT
(
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    CONTACT_NO,
    DOB,
    ADDRESS,
    CITY,
    STATE,
    COUNTRY,
    REGISTRATION_DATE,
    LAST_UPDATED
)
VALUES
(
    S.CUSTOMER_ID,
    S.FIRST_NAME,
    S.LAST_NAME,
    S.EMAIL,
    S.CONTACT_NO,
    S.DOB,
    S.ADDRESS,
    S.CITY,
    S.STATE,
    S.COUNTRY,
    S.REGISTRATION_DATE,
    S.LAST_UPDATED
);
 /*End of Incremental Loading*/
   
