/*
=====================================================
Project : End-to-End Retail ETL Pipeline using Snowflake
Module  : Customer ETL
Author  : Shweta Mujmer
=====================================================
*/

/*COPY INTO RAW.PRODUCTS_STG*/

COPY INTO RAW.PRODUCTS_STG
FROM @RAW.RETAIL_STAGE/product.csv
FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_FILE_FORMAT')
ON_ERROR = 'CONTINUE';

/*Validation using ROW_NUMBER()*/


SELECT
    PRODUCT_ID,
    TRIM(PRODUCT_NAME) AS PRODUCT_NAME,
    TRIM(CATEGORY) AS CATEGORY,
    PRICE,
    STOCK_QUANTITY,
    TRIM(STATUS) AS STATUS,
    LAST_UPDATED
FROM
(
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY PRODUCT_ID
               ORDER BY LAST_UPDATED DESC
           ) AS RN
    FROM RAW.PRODUCTS_STG
)
WHERE RN = 1
  AND PRODUCT_ID IS NOT NULL
  AND PRODUCT_NAME IS NOT NULL
  AND CATEGORY IS NOT NULL
  AND STATUS IS NOT NULL
  AND STOCK_QUANTITY >= 0
  AND PRICE > 0;

  /*Insert valid records from RAW.PRODUCTS_STG into CURATED.PRODUCTS */


INSERT INTO CURATED.PRODUCTS
SELECT
    PRODUCT_ID,
    TRIM(PRODUCT_NAME) AS PRODUCT_NAME,
    TRIM(CATEGORY) AS CATEGORY,
    PRICE,
    STOCK_QUANTITY,
    TRIM(STATUS) AS STATUS,
    LAST_UPDATED
    FROM
(
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY PRODUCT_ID
               ORDER BY LAST_UPDATED DESC
           ) AS RN
    FROM RAW.PRODUCTS_STG
)
WHERE RN = 1
  AND PRODUCT_ID IS NOT NULL
  AND PRODUCT_NAME IS NOT NULL
  AND CATEGORY IS NOT NULL
  AND STATUS IS NOT NULL
  AND STOCK_QUANTITY >= 0
  AND PRICE > 0;

  /*End of Curated Load*/

  /*INSERT INTO REJECT.PRODUCTS_REJECT*/

  INSERT INTO REJECT.PRODUCTS_REJECT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    PRICE,
    STOCK_QUANTITY,
    STATUS,
    LAST_UPDATED,
    FILE_NAME, 
    REJECT_REASON,
    LOAD_TIMESTAMP
)

SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    PRICE,
    STOCK_QUANTITY,
    STATUS,
    LAST_UPDATED,
    
CASE
    WHEN RN > 1 THEN 'Duplicate PRODUCT_ID'
    WHEN PRODUCT_ID IS NULL THEN 'PRODUCT_ID is NULL'
    WHEN PRODUCT_NAME IS NULL THEN 'PRODUCT_NAME is NULL'
    WHEN PRICE <= 0  THEN 'PRICE must be greater than 0'
    WHEN STOCK_QUANTITY < 0  THEN 'STOCK_QUANTITY IS LESS THEN 0'
    WHEN STATUS IS NULL THEN 'Invalid STATUS'
    WHEN CATEGORY IS NULL THEN 'CATEGORY IS NULL'
END AS REJECT_REASON,
 'PRODUCT.csv' AS FILE_NAME,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP

FROM
(
    SELECT *,
           ROW_NUMBER() OVER
           (
               PARTITION BY PRODUCT_ID
               ORDER BY LAST_UPDATED DESC
           ) AS RN
    FROM RAW.PRODUCTS_STG
) 

WHERE RN > 1
   OR PRODUCT_ID IS NULL
   OR PRODUCT_NAME IS NULL
   OR CATEGORY IS NULL
   OR STATUS IS NULL
   OR PRICE <= 0  
   OR STOCK_QUANTITY < 0 
   ;

   /* Ends Reject Handling */

   /*MERGE INTO CURATED.PRODUCTS*/

   MERGE INTO CURATED.PRODUCTS AS T

USING
(
    SELECT *
    FROM
    (
        SELECT *,
               ROW_NUMBER() OVER
               (
                   PARTITION BY PRODUCT_ID
                   ORDER BY LAST_UPDATED DESC
               ) AS RN
        FROM RAW.PRODUCTS_STG
    )
 WHERE RN = 1
  AND PRODUCT_ID IS NOT NULL
  AND PRODUCT_NAME IS NOT NULL
  AND CATEGORY IS NOT NULL
  AND STATUS IS NOT NULL
  AND PRICE >= 0
  AND STOCK_QUANTITY >= 0
) AS S
ON T.PRODUCT_ID = S.PRODUCT_ID
WHEN MATCHED THEN
UPDATE SET
    T.PRODUCT_ID = S.PRODUCT_ID,
    T.PRODUCT_NAME = S.PRODUCT_NAME,
    T.CATEGORY = S.CATEGORY,
    T.PRICE = S.PRICE,
    T.STOCK_QUANTITY = S.STOCK_QUANTITY,
    T.STATUS = S.STATUS,
    T.LAST_UPDATED = S.LAST_UPDATED

WHEN NOT MATCHED THEN
INSERT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    PRICE,
    STOCK_QUANTITY,
    STATUS,
    LAST_UPDATED
)
VALUES
(
   S.PRODUCT_ID,
   S.PRODUCT_NAME,
   S.CATEGORY,
   S.PRICE,
   S.STOCK_QUANTITY,
   S.STATUS,
   S.LAST_UPDATED
);
 /*Ends Incremental Loading*/

