/*
=====================================================
Project : End-to-End Retail ETL Pipeline using Snowflake
Module  : Customer ETL
Author  : Shweta Mujmer
=====================================================
*/

/*COPY INTO RAW.ORDERS_STG*/

COPY INTO RAW.ORDERS_STG
FROM @RAW.RETAIL_STAGE/orders.csv
FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_FILE_FORMAT')
ON_ERROR = 'CONTINUE';

/*Validation using ROW_NUMBER()*/

SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    QUANTITY,
    ORDER_DATE,
    TOTAL_AMOUNT,
    ORDER_STATUS ,
    LAST_UPDATED
FROM
(
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY ORDER_ID
               ORDER BY LAST_UPDATED DESC
           ) AS RN
    FROM RAW.ORDERS_STG
)
WHERE RN = 1
  AND ORDER_ID IS NOT NULL
  AND PRODUCT_ID IS NOT NULL
  AND CUSTOMER_ID IS NOT NULL
  AND ORDER_STATUS IS NOT NULL
  AND ORDER_DATE IS NOT NULL
  AND QUANTITY > 0
  AND TOTAL_AMOUNT > 0;

/*Insert valid records from RAW.ORDERS_STG into CURATED.ORDERS*/


INSERT INTO CURATED.ORDERS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    QUANTITY,
    ORDER_DATE,
    ORDER_STATUS,
    TOTAL_AMOUNT,
    LAST_UPDATED
    FROM
(
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY ORDER_ID
               ORDER BY LAST_UPDATED DESC
           ) AS RN
    FROM RAW.ORDERS_STG
)
WHERE RN = 1
  AND ORDER_ID IS NOT NULL
  AND PRODUCT_ID IS NOT NULL
  AND CUSTOMER_ID IS NOT NULL
  AND ORDER_STATUS IS NOT NULL
  AND ORDER_DATE IS NOT NULL
  AND QUANTITY > 0
  AND TOTAL_AMOUNT > 0;

  /*End of Curated Load*/

  /*INSERTING DATA INTO REJECT ORDER TABLE*/

   INSERT INTO REJECT.ORDERS_REJECT
(
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    QUANTITY,
    ORDER_DATE,
    ORDER_STATUS,
    TOTAL_AMOUNT,
    LAST_UPDATED,
    FILE_NAME, 
    REJECT_REASON,
    LOAD_TIMESTAMP
)

SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    QUANTITY,
    ORDER_DATE,
    ORDER_STATUS,
    TOTAL_AMOUNT,
    LAST_UPDATED,
    
CASE
    WHEN RN > 1 THEN 'Duplicate ORDER_ID_ID'
    WHEN ORDER_ID IS NULL THEN 'ORDER_ID is NULL'
    WHEN PRODUCT_ID IS NULL THEN 'PRODUCT_ID is NULL'
    WHEN CUSTOMER_ID IS NULL THEN 'CUSTOMER_ID is NULL'
    WHEN TOTAL_AMOUNT < 0  THEN 'TOTAL_AMOUNT must be greater than 0'
    WHEN QUANTITY <= 0  THEN 'STOCK_QUANTITY IS LESS THEN 0'
    WHEN ORDER_STATUS IS NULL THEN 'Invalid STATUS'
    WHEN ORDER_DATE IS NULL THEN 'ORDER_DATE IS NULL'
END AS REJECT_REASON,
 'ORDER.csv' AS FILE_NAME,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP

FROM
(
    SELECT *,
           ROW_NUMBER() OVER
           (
               PARTITION BY ORDER_ID
               ORDER BY LAST_UPDATED DESC
           ) AS RN
    FROM RAW.ORDERS_STG
) 

WHERE RN > 1
   OR ORDER_ID IS NULL
   OR PRODUCT_ID IS NULL
   OR CUSTOMER_ID IS NULL
   OR ORDER_STATUS IS NULL
   OR ORDER_DATE IS NULL
   OR TOTAL_AMOUNT <= 0  
   OR QUANTITY < 0 
   ;

   /* Ends Rejct Handling*/

/*MERGE INTO CURATED.ORDERS*/

MERGE INTO CURATED.ORDERS AS T

USING
(
    SELECT *
    FROM
    (
        SELECT *,
               ROW_NUMBER() OVER
               (
                   PARTITION BY ORDER_ID
                   ORDER BY LAST_UPDATED DESC
               ) AS RN
        FROM RAW.ORDERS_STG
    )
 WHERE RN = 1
  AND ORDER_ID IS NOT NULL
  AND PRODUCT_ID IS NOT NULL
  AND CUSTOMER_ID IS NOT NULL
  AND ORDER_STATUS IS NOT NULL
  AND ORDER_DATE IS NOT NULL
  AND QUANTITY > 0
  AND TOTAL_AMOUNT > 0
) AS S
ON T.ORDER_ID = S.ORDER_ID
WHEN MATCHED THEN
UPDATE SET
   T.ORDER_ID = S.ORDER_ID,
   T.CUSTOMER_ID = S.CUSTOMER_ID,
   T.PRODUCT_ID = S.PRODUCT_ID,
   T.QUANTITY = S.QUANTITY,
   T.ORDER_DATE = S.ORDER_DATE,
   T.ORDER_STATUS = S.ORDER_STATUS,
   T.TOTAL_AMOUNT = S.TOTAL_AMOUNT,
   T.LAST_UPDATED = S.LAST_UPDATED
WHEN NOT MATCHED THEN
INSERT
(
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    QUANTITY,
    ORDER_DATE,
    ORDER_STATUS,
    TOTAL_AMOUNT,
    LAST_UPDATED
)
VALUES
(
    S.ORDER_ID,
    S.CUSTOMER_ID,
    S.PRODUCT_ID,
    S.QUANTITY,
    S.ORDER_DATE,
    S.ORDER_STATUS,
    S.TOTAL_AMOUNT,
    S.LAST_UPDATED
);
/* Ends Incremental Loading*/