/*
=====================================================
Project : End-to-End Retail ETL Pipeline using Snowflake
Module  : Customer ETL
Author  : Shweta Mujmer
=====================================================
*/

/*COPY INTO RAW.PAYMENTS_STG*/

COPY INTO RAW.PAYMENTS_STG
FROM @RAW.RETAIL_STAGE/Payments.csv
FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_FILE_FORMAT')
ON_ERROR = 'CONTINUE';

/*Validation using ROW_NUMBER()*/

SELECT
    PAYMENT_ID,
    ORDER_ID,
    PAYMENT_MODE,
    PAYMENT_DATE,
    PAYMENT_STATUS,
    AMOUNT,
    LAST_UPDATED
FROM
(
    SELECT *,
           ROW_NUMBER() OVER
           (
               PARTITION BY PAYMENT_ID
               ORDER BY LAST_UPDATED DESC
           ) AS RN
    FROM RAW.PAYMENTS_STG
)
WHERE RN = 1
  AND PAYMENT_ID IS NOT NULL
  AND ORDER_ID IS NOT NULL
  AND PAYMENT_MODE IS NOT NULL
  AND PAYMENT_DATE IS NOT NULL
  AND PAYMENT_STATUS IS NOT NULL
  AND AMOUNT > 0;

/*Insert valid records from RAW.PAYMENTS_STG into CURATED.PAYMENTS*/

INSERT INTO CURATED.PAYMENTS
SELECT
    PAYMENT_ID,
    ORDER_ID,
    PAYMENT_MODE,
    PAYMENT_DATE,
    PAYMENT_STATUS,
    AMOUNT,
    LAST_UPDATED
    FROM
(
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY PAYMENT_ID
               ORDER BY LAST_UPDATED DESC
           ) AS RN
    FROM RAW.PAYMENTS_STG
)
WHERE RN = 1
  AND PAYMENT_ID IS NOT NULL
  AND ORDER_ID IS NOT NULL
  AND PAYMENT_MODE IS NOT NULL
  AND PAYMENT_DATE IS NOT NULL
  AND PAYMENT_STATUS IS NOT NULL
  AND AMOUNT > 0;

/* End of Curated Load*/

/*INSERTING DATA INTO REJECT PAYMENT TABLE*/

  INSERT INTO REJECT.PAYMENTS_REJECT
(
    PAYMENT_ID,
    ORDER_ID,
    PAYMENT_MODE,
    PAYMENT_DATE,
    PAYMENT_STATUS,
    AMOUNT,
    LAST_UPDATED,
    FILE_NAME, 
    REJECT_REASON,
    LOAD_TIMESTAMP
)

SELECT
    PAYMENT_ID,
    ORDER_ID,
    PAYMENT_MODE,
    PAYMENT_DATE,
    PAYMENT_STATUS,
    AMOUNT,
    LAST_UPDATED,
    
CASE
    WHEN RN > 1 THEN 'Duplicate PAYMENT_ID'
    WHEN PAYMENT_ID IS NULL THEN 'PAYMENT_ID is NULL'
    WHEN ORDER_ID IS NULL THEN 'ORDER_ID is NULL'
    WHEN PAYMENT_MODE IS NULL THEN 'PAYMENT_MODE is NULL'
    WHEN PAYMENT_DATE IS NULL THEN 'PAYMENT_DATE is NULL'
    WHEN PAYMENT_STATUS IS NULL THEN 'PAYMENT_STATUS is NULL'
    WHEN AMOUNT < 0  THEN 'AMOUNT must be greater than 0'
    
END AS REJECT_REASON,
 'PAYMENT.csv' AS FILE_NAME,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP

FROM
(
    SELECT *,
           ROW_NUMBER() OVER
           (
               PARTITION BY PAYMENT_ID
               ORDER BY LAST_UPDATED DESC
           ) AS RN
    FROM RAW.PAYMENTS_STG
) 

WHERE RN > 1
   OR ORDER_ID IS NULL
   OR PAYMENT_ID IS NULL
   OR PAYMENT_MODE IS NULL
   OR PAYMENT_STATUS IS NULL
   OR PAYMENT_DATE IS NULL
   OR AMOUNT <= 0  
  ;

/*Ends Reject Handling */

/* MERGE FOR PAYMENT TABLE*/

MERGE INTO CURATED.PAYMENTS AS T

USING
(
    SELECT *
    FROM
    (
        SELECT *,
               ROW_NUMBER() OVER
               (
                   PARTITION BY PAYMENT_ID
                   ORDER BY LAST_UPDATED DESC
               ) AS RN
        FROM RAW.PAYMENTS_STG
    )
 WHERE RN = 1
  AND PAYMENT_ID IS NOT NULL
  AND ORDER_ID IS NOT NULL
  AND PAYMENT_MODE IS NOT NULL
  AND PAYMENT_DATE IS NOT NULL
  AND PAYMENT_STATUS IS NOT NULL
  AND AMOUNT > 0
) AS S
ON T.PAYMENT_ID = S.PAYMENT_ID
WHEN MATCHED THEN
UPDATE SET
T.PAYMENT_ID = S.PAYMENT_ID,
T.ORDER_ID = S.ORDER_ID,
T.PAYMENT_MODE = S.PAYMENT_MODE,
T.PAYMENT_DATE = S.PAYMENT_DATE,
T. PAYMENT_STATUS = S.PAYMENT_STATUS,
T.AMOUNT = S.AMOUNT,
T.LAST_UPDATED = S.LAST_UPDATED
WHEN NOT MATCHED THEN
INSERT
(
    PAYMENT_ID,
    ORDER_ID,
    PAYMENT_MODE,
    PAYMENT_DATE,
    PAYMENT_STATUS,
    AMOUNT,
    LAST_UPDATED
)
VALUES
(
    S.PAYMENT_ID,
    S.ORDER_ID,
    S.PAYMENT_MODE,
    S.PAYMENT_DATE,
    S.PAYMENT_STATUS,
    S.AMOUNT,
    S.LAST_UPDATED
);

/*Ends Incremental Loading  */

